import 'package:assignmenttwo/screens/menuscreen/models/product.dart';

class MyProduct {
  static List<Product> allProducts = [
     Product(
      id: 1,
      name: "Pizza",
      images: "assets/images/pizza.png",
      description: "pizza, dish of Italian origin consisting of a flattened disk of bread dough topped with some combination of olive oil, oregano, tomato, olives, mozzarella or other cheese, and many other ingredients, baked quickly—usually, in a commercial setting, using a wood-fired oven heated to a very high temperature—and served hot",
      price: 200,
      quantity: 1,
    ),
    Product(
      id: 1,
      name: "burgur",
      images: "assets/images/burger.png",
      description: "A burger is a patty of ground beef grilled and placed between two halves of a bun. Slices of raw onion, lettuce, bacon, mayonnaise, and other ingredients add flavor. Burgers are considered an American food but are popular around the world.",
      price: 200,
      quantity: 1,
    ),
    Product(
      id: 1,
      name: "RIce",
      images: "assets/images/rice.png",
      description: "Cooked sweet rice mixed with red beans, jujubes and chestnuts",
      price: 200,
      quantity: 1,
    ),
    Product(
      id: 1,
      name: "Juice",
      images: "assets/images/fresh.png",
      description: "A burger is a patty of ground beef grilled and placed between two halves of a bun. Slices of raw onion, lettuce, bacon, mayonnaise, and other ingredients add flavor. Burgers are considered an American food but are popular around the world.",
      price: 200,
      quantity: 1,
    ),
    Product(
      id: 1,
      name: "Pizza",
      images: "assets/images/pizza.png",
      description: "pizza, dish of Italian origin consisting of a flattened disk of bread dough topped with some combination of olive oil, oregano, tomato, olives, mozzarella or other cheese, and many other ingredients, baked quickly—usually, in a commercial setting, using a wood-fired oven heated to a very high temperature—and served hot",
      price: 200,
      quantity: 1,
    ),
    Product(
      id: 1,
      name: "burgur",
      images: "assets/images/burger.png",
      description: "A burger is a patty of ground beef grilled and placed between two halves of a bun. Slices of raw onion, lettuce, bacon, mayonnaise, and other ingredients add flavor. Burgers are considered an American food but are popular around the world.",
      price: 200,
      quantity: 1,
    ),
    Product(
      id: 1,
      name: "RIce",
      images: "assets/images/rice.png",
      description: "Cooked sweet rice mixed with red beans, jujubes and chestnuts",
      price: 200,
      quantity: 1,
    ),
    Product(
      id: 1,
      name: "Juice",
      images: "assets/images/fresh.png",
      description: "A burger is a patty of ground beef grilled and placed between two halves of a bun. Slices of raw onion, lettuce, bacon, mayonnaise, and other ingredients add flavor. Burgers are considered an American food but are popular around the world.",
      price: 200,
      quantity: 1,
    ),
    Product(
      id: 1,
      name: "Pizza",
      images: "assets/images/pizza.png",
      description: "pizza, dish of Italian origin consisting of a flattened disk of bread dough topped with some combination of olive oil, oregano, tomato, olives, mozzarella or other cheese, and many other ingredients, baked quickly—usually, in a commercial setting, using a wood-fired oven heated to a very high temperature—and served hot",
      price: 200,
      quantity: 1,
    ),
    Product(
      id: 1,
      name: "burgur",
      images: "assets/images/burger.png",
      description: "A burger is a patty of ground beef grilled and placed between two halves of a bun. Slices of raw onion, lettuce, bacon, mayonnaise, and other ingredients add flavor. Burgers are considered an American food but are popular around the world.",
      price: 200,
      quantity: 1,
    ),
    Product(
      id: 1,
      name: "RIce",
      images: "assets/images/rice.png",
      description: "Cooked sweet rice mixed with red beans, jujubes and chestnuts",
      price: 200,
      quantity: 1,
    ),
    Product(
      id: 1,
      name: "Juice",
      images: "assets/images/fresh.png",
      description: "A burger is a patty of ground beef grilled and placed between two halves of a bun. Slices of raw onion, lettuce, bacon, mayonnaise, and other ingredients add flavor. Burgers are considered an American food but are popular around the world.",
      price: 200,
      quantity: 1,
    ),
  ];
}